### ISSUE TITLE
Use of Salesforce Branding

### ISSUE THREAD

**Issue by ntotten** [jatinsharmaa/CodeSnippetsforSalesforce#57]
Please remove the Salesforce logo from this extension. The use of our logo, font, colors, etc. is not permitted. Additionally, for clarity please call the extension something like "Code Snippets for Salesforce Platform" instead of "Salesforce XZY" as the latter implies that this is an official extension.

Otherwise, this looks great. Thanks for the contribution!

**Comment by jatinsharmaa** [comment]
Hi @ntotten, thank you for you recommendation. We have made the requested changes to our tool.
